default: true

# Line length
# https://github.com/DavidAnson/markdownlint/blob/main/doc/Rules.md#md013
MD013: false

# Dollar signs used before commands without showing output
# https://github.com/DavidAnson/markdownlint/blob/main/doc/Rules.md#md014
MD014: false

# Emphasis used instead of a heading
# https://github.com/DavidAnson/markdownlint/blob/main/doc/Rules.md#md036
MD036: false
