[tool.poetry]
name = "problem-matcher"
version = "0.0.0"
description = "A CLI tool for testing GitHub problem matcher configurations"
authors = ["norosa <23469+norosa@users.noreply.github.com>"]
repository = "https://github.com/bottle-garden/problem-matcher"
readme = "README.md"
keywords = [ "testing", "ci-cd", "text-processing", "qa-automation" ]
classifiers = [
  "Development Status :: 1 - Planning",
  "Environment :: Console",
  "Intended Audience :: Information Technology",
  "License :: OSI Approved :: Apache Software License",
  "Programming Language :: Python :: 3",
  "Topic :: Software Development :: Quality Assurance",
  "Topic :: Software Development :: Testing",
  "Topic :: Utilities"
]
packages = [
  { include = "pmatch", "from" = "src" },
]

[tool.poetry.dependencies]
python = "^3.7"

[tool.poetry.dev-dependencies]
black = "^21.9b0"

[build-system]
build-backend = "poetry.core.masonry.api"
requires = ["poetry-core>=1.0.0"]

[tool.poetry.scripts]
pmatch= "pmatch.cli:run"
