title: 'EditorConfig'
formats:
  txt:
    syntax: regex
    severities:
      notice:
        match: '^(.*):(.*):(.*): note: (.*) \[(.*)\]$'
      warning:
        match: '^(.*):(.*):(.*): warning: (.*) \[(.*)\]$'
      error:
        match: '^(.*):(.*):(.*): error: (.*) \[(.*)\]$'
    match-attrs:
      file: '{0}'
      line: '{1}'
      title: 'ShellCheck: {4}'
      message: '{3}'
