name: Build
on:
  pull_request:
  push:
    branches:
      - main

jobs:
  build:
    name: Run tests
    runs-on: ubuntu-latest
    container:
      image: nomiro/devcontainers:universal
    steps:
      - uses: actions/checkout@v3
      - run: make lint
