name: Build
on:
  pull_request:
  push:
    branches:
      - main

jobs:
  create-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: docker/metadata-action@v3
        id: meta
        with:
          images: ghcr.io/${{ github.repository }}/devcontainer
          tags: |
            type=ref,event=branch
            type=ref,event=pr
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/build-push-action@v2
        with:
          context: .devcontainer
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          secrets: GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }}
  delete-image:
    needs: create-image
    runs-on: ubuntu-latest
    steps:
      - uses: chipkent/action-cleanup-package@v1.0.1
        with:
          package-name: ghcr.io/${{ github.repository }}/devcontainer
          tag: pr-${{ github.event.pull_request.number }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
