name: Push
on:
  pull_request:
  push:
    branches:
      - main

jobs:
  build:
    name: Integration tests
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/bottle-garden/gh-vscode/devcontainer:universal
    steps:
      - uses: actions/checkout@v2
      - run: make lint
