name: Push
on:
  pull_request:
  push:
    branches:
      - main

jobs:
  logs:
    name: Logs
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: echo "::add-matcher::tests/matchers/shellcheck-gcc.json"
    - run: cat tests/output/shellcheck-gcc.txt
